{{- if and (or .Values.mongodb.auth.enabled .Values.redis.auth.enabled) (not .Values.mongodb.auth.existingSecret) (not .Values.redis.auth.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "yousoon-storage.fullname" . }}-secrets
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "yousoon-storage.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.mongodb.auth.enabled }}
  mongodb-root-password: {{ .Values.mongodb.auth.rootPassword | default "changeme" | b64enc | quote }}
  {{- end }}
  {{- if .Values.redis.auth.enabled }}
  redis-password: {{ .Values.redis.auth.password | default "changeme" | b64enc | quote }}
  {{- end }}
  {{- if and .Values.elasticsearch.security.enabled .Values.elasticsearch.security.password }}
  elasticsearch-password: {{ .Values.elasticsearch.security.password | b64enc | quote }}
  {{- end }}
{{- end }}
