# =============================================================================
# Yousoon Sites Chart
# =============================================================================
# DÃ©ploie les sites web:
# - admin (backoffice)
# - partners (portail partenaires)
# - website (site vitrine)
# =============================================================================

apiVersion: v2
name: yousoon-sites
description: Yousoon Web Sites (Admin, Partners, Vitrine)
type: application
version: 0.1.0
appVersion: "1.0.0"
