{{/*
# =============================================================================
# Yousoon Platform - Namespace
# =============================================================================
*/}}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.global.namespace }}
  labels:
    {{- include "yousoon.labels" . | nindent 4 }}
    environment: {{ .Values.global.environment | default "staging" }}
