# Jaeger - Configuration
allInOne:
  extraEnv:
    - name: COLLECTOR_OTLP_ENABLED
      value: "true"
    - name: SPAN_STORAGE_TYPE
      value: "memory"
    - name: MEMORY_MAX_TRACES
      value: "100000"
