# NATS - Production overrides
container:
  resources:
    requests:
      memory: 128Mi
      cpu: 100m
    limits:
      memory: 512Mi
      cpu: 500m

config:
  jetstream:
    memoryStore:
      maxSize: 512Mi
    fileStore:
      pvc:
        size: 20Gi
        storageClassName: gp3
