# Kustomization for Yousoon Kubernetes Deployment
# AWS ECR Registry: 771322424.dkr.ecr.eu-west-1.amazonaws.com
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: yousoon

# Resources to deploy
resources:
  - namespace.yaml
  - configmaps.yaml
  - secrets.template.yaml
  - ingress.yaml
  - monitoring.yaml

# Common labels for all resources
commonLabels:
  app.kubernetes.io/name: yousoon
  app.kubernetes.io/part-of: yousoon
  app.kubernetes.io/managed-by: kustomize

# Images - AWS ECR (version 2.x.x)
images:
  - name: identity-service
    newName: 771322424.dkr.ecr.eu-west-1.amazonaws.com/yousoon-identity-service
    newTag: "2.0.0"
  - name: partner-service
    newName: 771322424.dkr.ecr.eu-west-1.amazonaws.com/yousoon-partner-service
    newTag: "2.0.0"
  - name: discovery-service
    newName: 771322424.dkr.ecr.eu-west-1.amazonaws.com/yousoon-discovery-service
    newTag: "2.0.0"
  - name: booking-service
    newName: 771322424.dkr.ecr.eu-west-1.amazonaws.com/yousoon-booking-service
    newTag: "2.0.0"
  - name: engagement-service
    newName: 771322424.dkr.ecr.eu-west-1.amazonaws.com/yousoon-engagement-service
    newTag: "2.0.0"
  - name: notification-service
    newName: 771322424.dkr.ecr.eu-west-1.amazonaws.com/yousoon-notification-service
    newTag: "2.0.0"
  - name: apollo-router
    newName: 771322424.dkr.ecr.eu-west-1.amazonaws.com/yousoon-router
    newTag: "2.0.0"
  - name: web-partners
    newName: 771322424.dkr.ecr.eu-west-1.amazonaws.com/yousoon-web-partners
    newTag: "2.0.0"
  - name: web-admin
    newName: 771322424.dkr.ecr.eu-west-1.amazonaws.com/yousoon-web-admin
    newTag: "2.0.0"

# ConfigMap generators (if needed)
# configMapGenerator:
#   - name: app-config
#     files:
#       - config.json

# Secret generators (if needed)
# secretGenerator:
#   - name: app-secrets
#     files:
#       - secrets.env
